var dados_grid = [
    { pos: 1, piloto: "Carlos Sainz", equipe: "Ferrari", tempo: "01:04.069", diferenca: "-", voltas: "-" },
    { pos: 2, piloto: "Lord", equipe: "Sauber", tempo: "01:04.917", diferenca: "-", voltas: "-" },
    { pos: 3, piloto: "Sergio Perez", equipe: "RBR", tempo: "01:05.718", diferenca: "-", voltas: "-" },
    { pos: 4, piloto: "Pierre Gasly", equipe: "RBR", tempo: "01:06.712", diferenca: "-", voltas: "-" },
    { pos: 5, piloto: "Max Verstappen", equipe: "RBR", tempo: "01:06.953", diferenca: "-", voltas: "-" },
    { pos: 6, piloto: "Sebastian Vettel", equipe: "Ferrari", tempo: "01:07.087", diferenca: "-", voltas: "-" },
    { pos: 7, piloto: "Yuki Tsunoda", equipe: "RBR", tempo: "01:07.193", diferenca: "-", voltas: "-" },
    { pos: 8, piloto: "Charles Leclerc", equipe: "Ferrari", tempo: "01:07.598", diferenca: "-", voltas: "-" },
    { pos: 9, piloto: "Felipe Massa", equipe: "Ferrari", tempo: "01:08.141", diferenca: "-", voltas: "-" },
    { pos: 10, piloto: "Fernando Alonso", equipe: "Ferrari", tempo: "01:08.544", diferenca: "-", voltas: "-" },
    { pos: 11, piloto: "Marvin Renchet", equipe: "RBR", tempo: "01:08.512", diferenca: "-", voltas: "-" },
    { pos: 12, piloto: "Marco Hernandez", equipe: "Ferrari", tempo: "01:10.112", diferenca: "-", voltas: "-" },
    { pos: 13, piloto: "Christopher Dubert", equipe: "Ferrari", tempo: "01:10.976", diferenca: "-", voltas: "-" },
    { pos: 14, piloto: "Tamakoto Arai", equipe: "Ferrari", tempo: "01:12.226", diferenca: "-", voltas: "-" },
    { pos: 15, piloto: "Martin Hlisnikovsky", equipe: "Ferrari", tempo: "01:08.472", diferenca: "-", voltas: "-" },
    { pos: 16, piloto: "Valtteri Bottas", equipe: "Mercedes", tempo: "01:05.885", diferenca: "-", voltas: "-" },
    { pos: 17, piloto: "Nico Hulkenberg", equipe: "Renault", tempo: "01:02.10.144", diferenca: "-", voltas: "-" },
    { pos: 18, piloto: "Lance Stroll", equipe: "Aston Martin", tempo: "01:02.19.444", diferenca: "-", voltas: "-" },
    { pos: 19, piloto: "George Russell", equipe: "Mercedes", tempo: "01:02.20.144", diferenca: "-", voltas: "-" },
    { pos: 20, piloto: "Robert Kubica", equipe: "Williams", tempo: "01:02.21.311", diferenca: "-", voltas: "-" }
];
